FROM python:3.10 AS build

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
ENV base="btc"
ENV quote="usdt"
ENV threshold="1"
ENV cooldown="300"
ENV log_level="info"
ENV log_file="/dev/null"

CMD /usr/local/bin/python arbitrage-gossip/main.py \
  --base=${base} \
  --quote=${quote} \
  --cooldown=${cooldown} \
  --log-level=${log_level} \
  --log-file=${log_file}
